### ISSUE TITLE
Fixing links of project websites

### ISSUE THREAD

**Issue by shravan91** [DatameetAMD/DatameetAMD.github.io#9]
@gnatih

Fixing the links pointing to both these projects:

> Shuttle Rickshaw Project
> Open Loo Project

cc @ndkcha @jimishio

**Comment by gnatih** [comment]
This should be fixed for OpenLoo project in the last pull request. Shuttle Rickshaw Project does not have a project microsite, yet.

**Comment by shravan91** [comment]
@gnatih 

It is still not fixed. The link on the current website points [here](https://openahmedabad.org/open-loo#)
